### ISSUE TITLE
Guide to running showcase locally is missing a step

### ISSUE THREAD

**Issue by chrisco484** [adessoSE/wicked-charts#192]
The steps provided are:

1. Clone this Git repository.
2. Run gradle build wicked-charts-showcase-wicket7:bootRun inside the showcase directory (change wicket7 to wicket14, wicket15, wicket6 or wicket8 for the different versions).
3. Go to localhost:8080

but if you follow these steps diligently it can't work because it needs another step in between 1 - 2, (step 1.5 :) ) which is this:

1. 5  At the base directory of the project build the entire project using 
`gralew build`

Without first building the project from the base directory the showcase will be missing most of its core dependencies.

I also suggest using gradlew instead of gradle because the project seems to specify Gradle 4.10 and people with later versions may not have much luck unless gradle wrapper is used to run the older version.

BTW - Great library - I'm achieving great things with it in a very small amount of time!

**Comment by maximAtanasov** [comment]
Thank you for the positive feedback and for pointing out the mistake. I've updated the guide now.

**Comment by chrisco484** [comment]
> Thank you for the positive feedback and for pointing out the mistake. I've updated the guide now.

No problem. Thanks for providing this Wicket wrapper for Charts.js and making it so easy to use.
